course_examples = { 
    "q": "Learn how to make a video game, from idea to publication.",
    "nlp": "The bloom of Large Language Models (LLMs) has brought a starring breakthrough to \
    Natural Language Processing (NLP). In this course, students will delve into the conceptual and \
    technical advances of frontier LLM-based NLP technologies, revolutionizing classical computational \
    linguistics and NLP fields.",
     "graphics": "The class covers the following topics: Displays, Image processing, Affine transformations, Hierarchical modeling, Projections, Shading, Ray tracing, Texture mapping, Curves, Particle systems, Surfaces, and Animation.",
     "robot": "Can a Robot Be Divine? Will humans merge with technologies that enable them to transcend current reality? This course will engage with these questions and others as we survey philosophical concepts, ethical principles, and popular culture connecting AI and religion.",
      "interview": "Preparing for new grad system design interviews.",
      "shirt": "How to screen print a shirt with custom designs.",
      "vr": " first define the problem you are trying to solve. Would people want to use it? Would it bring them joy and delight? Would it improve their lives? Would it be fun? \
Also think about each device category carefully, and what features it offers. e.g. Headsets are more immersive, but not as widely available. Phones are less immersive, but easy to use and almost everyone has one. It may also be possible to think of ideas that combine multiple devices. You could also imagine using extra hardware, sensors or instruments. Our primary device for the class will be the Oculus Quest 2 but we can support project ideas with other devices as well. \
Here are some more questions to think about: Who is the intended audience? How would you know you are successful? What are current solutions or why isn't this problem already solved? What does the VR/AR medium provide that is not possible/ or easy to do through other medium?",
    "vision": "Ever wonder how robots can navigate space and perform duties, how search engines can index billions of images and videos, how algorithms can diagnose medical images for diseases, how self-driving cars can see and drive safely or how instagram creates filters or snapchat creates masks? In this class, we will explore all of these technologies and learn to prototype them. Lying in the heart of these modern AI applications are computer vision technologies that can perceive, understand and reconstruct the complex visual world. Computer Vision is one of the fastest growing and most exciting AI disciplines in today’s academia and industry. This 10-week course is designed to open the doors for students who are interested in learning about the fundamental principles and important applications of computer vision. We will expose students to a number of real-world applications that are important to our daily lives. More importantly, we will guide students through a series of well designed projects such that they will get to implement a few interesting and cutting-edge computer vision algorithms.",
    "guitar": "Learn fundamental electric guitar techniques and iconic songs",
    "system": "In this course, we design a messaging system to demonstrate the concepts. Starting with the fundamentals, we will gradually evolve the system throughout the course, introduce and explore different design concepts that address the defined problems, deep dive into the details of every concept and discuss trade-offs. Then continue the process over and over again. By following the process, you will understand the concepts and learn how they apply concepts to real cases. \
                The messaging system is a perfect example to learn the system design concepts. Messaging systems are used as building blocks for many distributed systems these days. Various smaller components of a distributed system communicate with each other using a messaging system. Systems themselves talk to each other using messaging systems. Which makes messaging systems play a critical role in system design. You'll learn how to build a reliable, scalable, secure, fast, easy-to-maintain, and low-dollar-cost system in the course. Then apply knowledge to building other distributed systems., \
                You will not be limited to the design principles used just in messaging systems. When looking at a specific design concept, we will go beyond how messaging systems use it. So that you can see relevant examples of how this and similar concepts are used in other systems.",
    }

sample_input = "{\"weeks\":[{\"week_index\": 1, \"topic\": \"The Bloom of Large Language Models (LLMs) in NLP\", \"assignments\": [{\"title\": \"Understanding Large Language Models (LLMs)\", \"estimated_time\": \"3 hours\", \"youtube_queries\": [\"Large Language Models explained\", \"Transformers in NLP\", \"BERT model explained\"], \"learning_goals\": \"Gain a solid understanding of the concept and importance of Large Language Models in NLP\"}, {\"title\": \"Applications of Large Language Models\", \"estimated_time\": \"4 hours\", \"youtube_queries\": [\"GPT-3 use cases\", \"Applications of BERT model\", \"Transformer models in real-world applications\"], \"learning_goals\": \"Explore various applications of Large Language Models and how they are used in real-world scenarios\"}, {\"title\": \"Challenges and Opportunities with Large Language Models\", \"estimated_time\": \"2 hours\", \"youtube_queries\": [\"Ethical concerns of LLMs\", \"Bias in Large Language Models\", \"Future of Large Language Models\"], \"learning_goals\": \"Understand the ethical considerations, challenges, and future directions associated with Large Language Models\"}], \"youtube_queries\": [\"Large Language Models in NLP\", \"BERT model applications\", \"Challenges of Large Language Models\"]}]}"
sample_search_result = {'kind': 'youtube#searchListResponse', 'etag': 'p06cwGuZjqcy5U-d0W84nbFji4w', 'nextPageToken': 'CAMQAA', 'regionCode': 'US', 'pageInfo': {'totalResults': 1000000, 'resultsPerPage': 3}, 'items': [{'kind': 'youtube#searchResult', 'etag': 'dBeaCpPS05-cMz13pHuWnYEN084', 'id': {'kind': 'youtube#video', 'videoId': '5sLYAQS9sWQ'}, 'snippet': {'publishedAt': '2023-07-28T13:13:59Z', 'channelId': 'UCKWaEZ-_VweaEx1j62do_vQ', 'title': 'How Large Language Models Work', 'description': 'Learn about watsonx → https://ibm.biz/BdvxRj Large language models-- or LLMs --are a type of generative pretrained transformer ...', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/5sLYAQS9sWQ/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/5sLYAQS9sWQ/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/5sLYAQS9sWQ/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': 'IBM Technology', 'liveBroadcastContent': 'none', 'publishTime': '2023-07-28T13:13:59Z'}}, {'kind': 'youtube#searchResult', 'etag': 'dtCCX0PlR8NQDaNeGVBipWjQHNg', 'id': {'kind': 'youtube#video', 'videoId': 'ToaPk3bO6Lc'}, 'snippet': {'publishedAt': '2024-01-02T12:19:13Z', 'channelId': 'UC3Jc8mVtCcLAnk3ZKyVahjA', 'title': 'OpinionGPT: Exploring the Impact of Biases on Large Language Models - Ansar Aynetdinov', 'description': 'Human biases inevitably get picked up by Large Language Models (LLMs). Consequently, a considerable amount of AI research ...', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/ToaPk3bO6Lc/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/ToaPk3bO6Lc/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/ToaPk3bO6Lc/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': 'Women Techmakers Berlin', 'liveBroadcastContent': 'none', 'publishTime': '2024-01-02T12:19:13Z'}}, {'kind': 'youtube#searchResult', 'etag': 'Yq432GRDtoM6ibpI4ZvU9jOFgLQ', 'id': {'kind': 'youtube#video', 'videoId': 'Qm--_1M_Uvk'}, 'snippet': {'publishedAt': '2023-06-12T14:59:05Z', 'channelId': 'UCrczXRwqa9bGfSBolPDt2ZQ', 'title': 'Evaluation: Bias &amp; Toxicity', 'description': 'A cursory introduction to the types of work on evaluating bias and fairness in language models and the systems in which they are ...', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/Qm--_1M_Uvk/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/Qm--_1M_Uvk/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/Qm--_1M_Uvk/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': 'Generative AI at MIT', 'liveBroadcastContent': 'none', 'publishTime': '2023-06-12T14:59:05Z'}}]}