course_examples = { 
    "q": "Learn how to make a video game, from idea to publication.",
    "nlp": "The bloom of Large Language Models (LLMs) has brought a starring breakthrough to \
    Natural Language Processing (NLP). In this course, students will delve into the conceptual and \
    technical advances of frontier LLM-based NLP technologies, revolutionizing classical computational \
    linguistics and NLP fields.",
     "graphics": "The class covers the following topics: Displays, Image processing, Affine transformations, Hierarchical modeling, Projections, Shading, Ray tracing, Texture mapping, Curves, Particle systems, Surfaces, and Animation.",
     "robot": "Can a Robot Be Divine? Will humans merge with technologies that enable them to transcend current reality? This course will engage with these questions and others as we survey philosophical concepts, ethical principles, and popular culture connecting AI and religion.",
      "interview": "Preparing for new grad system design interviews.",
      "shirt": "How to screen print a shirt with custom designs.",
      "vr": " first define the problem you are trying to solve. Would people want to use it? Would it bring them joy and delight? Would it improve their lives? Would it be fun? \
Also think about each device category carefully, and what features it offers. e.g. Headsets are more immersive, but not as widely available. Phones are less immersive, but easy to use and almost everyone has one. It may also be possible to think of ideas that combine multiple devices. You could also imagine using extra hardware, sensors or instruments. Our primary device for the class will be the Oculus Quest 2 but we can support project ideas with other devices as well. \
Here are some more questions to think about: Who is the intended audience? How would you know you are successful? What are current solutions or why isn't this problem already solved? What does the VR/AR medium provide that is not possible/ or easy to do through other medium?"   
    }

sample_input = "{\"weeks\":[{\"week_index\": 1, \"topic\": \"The Bloom of Large Language Models (LLMs) in NLP\", \"assignments\": [{\"title\": \"Understanding Large Language Models (LLMs)\", \"estimated_time\": \"3 hours\", \"youtube_queries\": [\"Large Language Models explained\", \"Transformers in NLP\", \"BERT model explained\"], \"learning_goals\": \"Gain a solid understanding of the concept and importance of Large Language Models in NLP\"}, {\"title\": \"Applications of Large Language Models\", \"estimated_time\": \"4 hours\", \"youtube_queries\": [\"GPT-3 use cases\", \"Applications of BERT model\", \"Transformer models in real-world applications\"], \"learning_goals\": \"Explore various applications of Large Language Models and how they are used in real-world scenarios\"}, {\"title\": \"Challenges and Opportunities with Large Language Models\", \"estimated_time\": \"2 hours\", \"youtube_queries\": [\"Ethical concerns of LLMs\", \"Bias in Large Language Models\", \"Future of Large Language Models\"], \"learning_goals\": \"Understand the ethical considerations, challenges, and future directions associated with Large Language Models\"}], \"youtube_queries\": [\"Large Language Models in NLP\", \"BERT model applications\", \"Challenges of Large Language Models\"]}]}"
